<?xml version="1.0"?>
<robot name="wheel" xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:property name="wheeldiam" value="0.3" />

<xacro:macro name="drive_wheel" params="location parent *origin">
	<link name="${location}_wheel">
  		<visual>
    		<origin xyz="0 0 0" rpy="${pi/2} 0 0" />
    		<geometry>
      			<cylinder radius="${wheeldiam/2}" length="${wheeldiam/4}"/>
    		</geometry>
  		</visual>
  		<collision>
    		<origin xyz="0 0 0" rpy="${pi/2} 0 0" />
    		<geometry>
      			<cylinder radius="${wheeldiam/2}" length="${wheeldiam/4}"/>
    		</geometry>
  		</collision>
		<inertial>
			<mass value="1" />
			<inertia ixx="15.0" ixy="0" ixz="0" iyy="15.0" iyz="0" izz="0.045" />
		</inertial>
	</link>
	<joint name="${location}_wheel_joint" type="continuous">
  		<axis xyz="0 1 0" rpy="0 0 0" />
  		<parent link="${parent}"/>
  		<child link="${location}_wheel"/>
		<xacro:insert_block name="origin"/>
	</joint>
	<gazebo reference="${location}_wheel">
  		<mu1 value="200.0"/>
 	 	<mu2 value="100.0"/>
  		<kp value="10000000.0" />
  		<kd value="1.0" />
  		<material>Gazebo/Grey</material>
	</gazebo>
	<transmission name="${location}_wheel_trans">
  		<type>transmission_interface/SimpleTransmission</type>
  		<actuator name="${location}_wheel_motor">
    		<mechanicalReduction>1</mechanicalReduction>
  		</actuator>
  		<joint name="${location}_wheel_joint">
    		<hardwareInterface>VelocityJointInterface</hardwareInterface>
  		</joint>
	</transmission>
</xacro:macro>

<xacro:macro name="caster_wheel" params="location parent *origin">
	<link name="${location}_wheel">
		<visual>
			<geometry>
				<sphere radius="${(wheeldiam-robot_side/2)/2}"/>
			</geometry>
		</visual>
		<collision>
			<geometry>
				<sphere radius="${(wheeldiam-robot_side/2)/2}"/>
			</geometry>
		</collision>
		<inertial>
			<mass value="1" />
			<inertia ixx="0.0025" ixy="0" ixz="0" iyy="0.0025" iyz="0" izz="0.0025" />
		</inertial>
	</link>
	<joint name="base_to_${location}_wheel" type="continuous">
		<axis xyz="0 1 0" rpy="0 0 0" />
    	<parent link="${parent}"/>
    	<child link="${location}_wheel"/>
  		<xacro:insert_block name="origin"/>
	</joint>
	<gazebo reference="${location}_wheel">
    	<mu1 value="1.0"/>
    	<mu2 value="0.5"/>
    	<kp value="10000000.0" />
    	<kd value="1.0" />
    	<material>Gazebo/Grey</material>
  	</gazebo>
</xacro:macro>

</robot>
